POST http://localhost:4000/comprar/createCom HTTP/1.1
content-type: application/json

{
    "fecha_compra":"28/08/2024",
    "fecha_devolucion":"29/08/2024",
    "estado":"Bien",
    "id_usuarios":"1",
    "id_productos":"1",
    "id_proveedor":"1"
}